
// This file was auto-generated by ML.NET Model Builder. 

using Model_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
Model.ModelInput sampleData = new Model.ModelInput()
{
    Col0 = @"大風",
    Col1 = @"音樂",
    Col2 = @"遠足",
    Col3 = @"足球",
    Col4 = @"葡萄牙",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col5 with predicted Col5 from sample data...\n\n");


Console.WriteLine($"Col0: {@"大風"}");
Console.WriteLine($"Col1: {@"音樂"}");
Console.WriteLine($"Col2: {@"遠足"}");
Console.WriteLine($"Col3: {@"足球"}");
Console.WriteLine($"Col4: {@"葡萄牙"}");
Console.WriteLine($"Col5: {@"太魯閣"}");


var sortedScoresWithLabel = Model.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

